# Auto-generated by AgentPort — do not edit manually.
# Agent : patient_intake v1.0.0
# Compliance: HIPAA, SOC2
"""
Audit logging for patient_intake.

Every node entry/exit and API invocation is logged as a structured JSON line.
Set AUDIT_LOG_TO_FILE=1 and AUDIT_LOG_PATH to write to a file instead of stdout.
HIPAA note: Do NOT log raw PHI values here. Log IDs, counts, and event types only.
"""
from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timezone
from typing import Any

_logger = logging.getLogger("agentport.audit.patient_intake")

# Prevent duplicate handlers if module is reloaded in tests
if not _logger.handlers:
    _use_file = os.getenv("AUDIT_LOG_TO_FILE", "").lower() in ("1", "true", "yes")
    _log_path = os.getenv("AUDIT_LOG_PATH", "/var/log/patient_intake/audit.jsonl")
    if _use_file:
        os.makedirs(os.path.dirname(_log_path), exist_ok=True)
        _handler: logging.Handler = logging.FileHandler(_log_path)
    else:
        _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("%(message)s"))
    _logger.addHandler(_handler)
    _logger.setLevel(logging.INFO)
    _logger.propagate = False


def log_event(
    event_type: str,
    agent: str,
    details: dict[str, Any],
    user_id: str | None = None,
) -> None:
    """Emit a single structured audit event."""
    entry: dict[str, Any] = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "event_type": event_type,
        "agent": agent,
        "user_id": user_id,
        "details": details,
    }
    _logger.info(json.dumps(entry, default=str))
