# Auto-generated by AgentPort — do not edit manually.
# Agent : patient_intake v1.0.0
from __future__ import annotations

import os

from langchain_core.messages import SystemMessage, HumanMessage
from langchain_anthropic import ChatAnthropic
from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import ToolNode

from .state import AgentState
from .tools import ALL_TOOLS, verify_insurance, check_availability, schedule_appointment
from .audit import log_event


# ── LLM factory ───────────────────────────────────────────────────────────────

def _build_llm():
    provider = os.getenv("LLM_PROVIDER", "openai")
    model = os.getenv("LLM_MODEL", "gpt-4o")
    if provider == "anthropic":
        return ChatAnthropic(
            model=model,
            temperature=0.2,
            max_tokens=1024,
            api_key=os.getenv("ANTHROPIC_API_KEY"),
        )
    if provider == "openai":
        return ChatOpenAI(
            model=model,
            temperature=0.2,
            api_key=os.getenv("OPENAI_API_KEY"),
        )
    raise ValueError(f"Unknown LLM_PROVIDER: {provider!r}")

# ── node definitions ──────────────────────────────────────────────────────────
_intake_agent_tools = [verify_insurance, check_availability, schedule_appointment]
_intake_agent_system = SystemMessage(content="""\
You are a HIPAA-compliant patient intake assistant for a medical practice.
Your role is to:
1. Collect patient name, date of birth, reason for visit, and insurance ID.
2. Verify insurance coverage using the verify_insurance tool.
3. Check appointment availability using check_availability.
4. Schedule the appointment using schedule_appointment.
Be professional, empathetic, and concise. Never echo back PHI unnecessarily.\
""")

def _node_intake_agent(state: AgentState) -> dict:
    log_event("node_enter", "patient_intake", {"node": "intake_agent"})
    _llm = _build_llm()
    _bound = _llm.bind_tools(_intake_agent_tools) if _intake_agent_tools else _llm
    messages = list(state.get("messages", []))
    if not messages or not isinstance(messages[0], SystemMessage):
        messages = [_intake_agent_system] + messages
    response = _bound.invoke(messages)
    n_tool_calls = len(getattr(response, "tool_calls", []) or [])
    log_event("node_exit", "patient_intake", {"node": "intake_agent", "tool_calls": n_tool_calls})
    return {"messages": [response]}

# ── routing functions ─────────────────────────────────────────────────────────

def _route_intake_agent(state: AgentState) -> str:
    msgs = state.get("messages", [])
    last = msgs[-1] if msgs else None
    if last and getattr(last, "tool_calls", None):
        return "tools"
    return "__end__"


# ── graph assembly ────────────────────────────────────────────────────────────

def build_graph():
    graph = StateGraph(AgentState)

    # Add nodes
    graph.add_node("intake_agent", _node_intake_agent)
    graph.add_node("tools", ToolNode(ALL_TOOLS))

    # Simple (unconditional) edges
    graph.add_edge(
        START,
        "intake_agent",
    )
    graph.add_edge(
        "tools",
        "intake_agent",
    )

    # Conditional edges
    graph.add_conditional_edges(
        "intake_agent",
        _route_intake_agent,
        {
            "tools": "tools",
            "__end__": END,
        },
    )

    return graph.compile()


# Module-level compiled graph — imported by main.py
graph_app = build_graph()
