# Auto-generated by AgentPort — do not edit manually.
# Agent : patient_intake v1.0.0
from __future__ import annotations

import uuid

from dotenv import load_dotenv
load_dotenv()  # must run before any module that reads env vars is imported

from fastapi import FastAPI, HTTPException
from langchain_core.messages import HumanMessage
from pydantic import BaseModel

from .audit import log_event
from .graph import graph_app

app = FastAPI(
    title="patient_intake",
    version="1.0.0",
    description="HIPAA-compliant patient intake agent for scheduling and insurance verification",
)


# ── request / response models ─────────────────────────────────────────────────

class InvokeRequest(BaseModel):
    message: str
    session_id: str | None = None


class InvokeResponse(BaseModel):
    response: str
    session_id: str


# ── endpoints ─────────────────────────────────────────────────────────────────

@app.get("/health")
async def health() -> dict:
    """Liveness probe — returns 200 when the service is ready."""
    return {"status": "ok", "agent": "patient_intake", "version": "1.0.0"}


@app.post("/invoke", response_model=InvokeResponse)
async def invoke(request: InvokeRequest) -> InvokeResponse:
    """
    Run one conversational turn through the patient_intake agent.

    The agent graph is stateless per-request; pass ``session_id`` for
    correlation in audit logs only — state persistence is not handled here.
    """
    session_id = request.session_id or str(uuid.uuid4())
    log_event("invoke_start", "patient_intake", {"session_id": session_id})
    try:
        result = graph_app.invoke(
            {"messages": [HumanMessage(content=request.message)]}
        )
        response_content: str = result["messages"][-1].content
        log_event(
            "invoke_end",
            "patient_intake",
            {"session_id": session_id, "ok": True},
        )
        return InvokeResponse(response=response_content, session_id=session_id)
    except Exception as exc:
        log_event(
            "invoke_error",
            "patient_intake",
            {"session_id": session_id, "error": str(exc)},
        )
        raise HTTPException(status_code=500, detail=str(exc)) from exc
