# Auto-generated by AgentPort — do not edit manually.
# Agent : patient_intake v1.0.0
# Source: HIPAA-compliant patient intake agent for scheduling and insurance verification
# Compliance: HIPAA, SOC2
from __future__ import annotations

from typing import Annotated, Any, Sequence
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class AgentState(dict):  # TypedDict-compatible dict for LangGraph
    """
    LangGraph state for patient_intake.

    All keys are optional at any given graph step; LangGraph merges partial
    updates returned by each node.
    """
    # [PHI] Full legal name of the patient
    # [PHI] Patient date of birth (YYYY-MM-DD)
    # Chief complaint or reason for visit
    # [PHI] Patient insurance member ID
    # Whether insurance has been verified
    # Confirmed appointment slot
    # Conversation message history
    # Type annotations (informational — LangGraph reads the class __annotations__)
    patient_name: str
    date_of_birth: str
    reason_for_visit: str
    insurance_id: str
    insurance_verified: bool
    appointment_slot: str
    messages: Annotated[Sequence[BaseMessage], add_messages]
    def __init__(self, **kwargs: Any) -> None:  # type: ignore[override]
        defaults: dict[str, Any] = {
            "insurance_verified": False,
            "messages": [],
        }
        defaults.update(kwargs)
        super().__init__(**defaults)


# Typed key constants — import these instead of bare strings to avoid typos.
PATIENT_NAME = "patient_name"
DATE_OF_BIRTH = "date_of_birth"
REASON_FOR_VISIT = "reason_for_visit"
INSURANCE_ID = "insurance_id"
INSURANCE_VERIFIED = "insurance_verified"
APPOINTMENT_SLOT = "appointment_slot"
MESSAGES = "messages"
